### PR TITLE
Docs tutorial info added

### PR DESCRIPTION
**Pull request by kushalbakshi**

### CODE REVIEW

**Comment by CBroz1** [comment]
I spoke with Drew who let me know that we only need to keep the `.github/.staging` directory and `.github/*sh` files in the Element Array Ephys, as the flagship element where we may need to recompile workflows. These can be removed from other repositories.

**Comment by kabilar** [comment]
Thanks @kushalbakshi! Please pull from upstream to fast forward your fork and we can then work towards merging this pull request.

**Comment by kushalbakshi** [comment]
Hi @kabilar, this PR can be closed. After fast forwarding, there are no changes left to be merged.

**Comment by kabilar** [comment]
Thanks for checking!

**Pull request closed without merging**
