### PR TITLE
blackify

### PR DESCRIPTION
**Pull request by CBroz1**

### CODE REVIEW

**Comment by kabilar** [comment]
Please update the changelog.  Thanks.

**Comment by CBroz1** [comment]
Odd 🤔 This PR isn't reflecting my second commit to this branch. I'll come back in a day to see if it catches up

image

**Comment by CBroz1** [comment]
@kabilar My branch shows 3 commits. Diffs here:
1. [blackify](https://github.com/CBroz1/element-miniscope/commit/826f8c80b1e45698c2bca30fd032126f00a9abed)
2. [version bump](https://github.com/CBroz1/element-miniscope/commit/039b7829dd5437f08fb42e62b0ef7276564b7887)
3. [test additional commit](https://github.com/CBroz1/element-miniscope/commit/0e26be2a03bd3570d99e66ed328e139b91885965) - condensed some pieces of gitignore (contents same, fewer headings) to see if middle commit would show in PR

The middle version bump isn't listed in the conversation history, but I see the edits in the Files Changed tab. Lmk if you want me to revert the third.

**Review by kabilar — APPROVED** [review]
Thanks @CBroz1!  Not sure why the changelog update did not initially show up, but everything looks good now.

**Pull request merged**
